решение модуля 0
js-tasks-ru/jsbasic-20220711_isandalov pull request #1
Opened 2022-07-10 16:18 UTC by isandalov

2022-07-10 16:18 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-07-12 07:10 UTC, SinimaWath requested changes

2022-07-12 07:10 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return console.log(sum)
`return console.log(sum)` - возвращает результат выполнения функции console.log, а он всегда равен undefined.

Поэтму надо писать: `return sum`

2022-07-12 07:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-14 11:56 UTC, SinimaWath approved these changes

2022-07-14 11:56 UTC, merged